# Banco PostgreSQL
quarkus.datasource.db-kind=<POSTGRESQL>
quarkus.datasource.username=<USUÁRIO>
quarkus.datasource.password=<SENHA>
quarkus.datasource.jdbc.url=<URL_DE_CONEXAO>


quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

